#!/usr/bin/env python3
"""Interactive setup: writes config.py for main.py."""

from colorama import Fore, Style, init

from utils import get_interface_list

init(autoreset=True)


def setup_wizard():
    print(
        Fore.GREEN
        + """
    ╔══════════════════════════════════════════════════════════╗
    ║                 SETUP WIZARD v1.0                        ║
    ║          Gaming Console Packet Sniffer                   ║
    ╚══════════════════════════════════════════════════════════╝
    """
    )

    print(Fore.YELLOW + "[+] Step 1: Network Interface Selection")
    interfaces = get_interface_list()

    for i, iface in enumerate(interfaces):
        print(f"{Fore.CYAN}[{i}] {iface}")

    choice = input(Fore.WHITE + "Select interface number: ").strip()
    selected_iface = interfaces[int(choice)]

    print(Fore.YELLOW + f"[+] Selected interface: {selected_iface}")

    print(Fore.YELLOW + "\n[+] Step 2: Target Game Selection")
    games = ["GTA5", "RDR2", "Battlefront2", "Fortnite", "WoLong"]

    for i, game in enumerate(games):
        print(f"{Fore.MAGENTA}[{i}] {game}")

    game_choices = input(Fore.WHITE + "Select games (comma-separated numbers): ").strip()
    selected_indices = [int(x.strip()) for x in game_choices.split(",")]
    selected_games = [games[i] for i in selected_indices]

    print(Fore.YELLOW + f"[+] Selected games: {', '.join(selected_games)}")

    print(Fore.YELLOW + "\n[+] Step 3: ARP Spoofing Configuration")
    enable_spoofing = input(Fore.WHITE + "Enable ARP spoofing? (y/n): ").strip()

    if enable_spoofing.lower() == "y":
        print(Fore.RED + "[!] ARP spoofing enabled — requires admin/root and may disrupt the LAN.")

    print(Fore.YELLOW + "\n[+] Step 4: Output Configuration")
    log_format = input(Fore.WHITE + "Log format (json/text/both): ").strip()

    game_ranges = {
        "GTA5": [6672, 61455, 61457, 61456, 61458],
        "RDR2": [3074, 6672, 61455],
        "Battlefront2": [3659, 10000, 20000],
        "Fortnite": [5222, 9999, 10000, 19000, 20000],
        "WoLong": [27015, 27016, 27017],
    }
    ranges_subset = {g: game_ranges[g] for g in selected_games if g in game_ranges}

    config_content = f'''# Generated by setup_wizard.py — edit by hand or re-run wizard

INTERFACE = {selected_iface!r}
ARP_SPOOFING = {str(enable_spoofing.lower() == "y")}

TARGET_GAMES = {selected_games!r}

GAME_PORT_RANGES = {ranges_subset!r}

LOG_FORMAT = {log_format!r}
'''

    with open("config.py", "w", encoding="utf-8") as f:
        f.write(config_content)

    print(Fore.GREEN + "\n[+] Configuration saved to config.py")
    print(Fore.GREEN + "[+] Run: source sniffer_env/bin/activate && sudo python3 main.py")
    print(Fore.GREEN + "    (or setcap on the venv python — see README.md / install.sh)")


if __name__ == "__main__":
    setup_wizard()
